language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    
language: java    
jdk:
  - oraclejdk8

services:
  - mysql

script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
notifications:
  email:
    recipients:
      - karthikeyan.p.k@lxisoft.com
    on_success: always # default: change
    on_failure: always # default: always
    
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: receptionist-app
 on: karthi
